version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
      - DEBUG=true
      # Variables de Odoo eliminadas del servicio API de test
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=dummy;AccountKey=dummy;EndpointSuffix=core.windows.net
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - miasalud_test

  workers:
    build:
      context: ..
      dockerfile: docker/Dockerfile.workers
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=true
      # Variables de Odoo eliminadas del servicio workers de test
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=dummy;AccountKey=dummy;EndpointSuffix=core.windows.net
    depends_on:
      - api
    networks:
      - miasalud_test

  test-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Test@123" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 60s
    networks:
      - miasalud_test

networks:
  miasalud_test:
    driver: bridge